In [8]:
import numpy as np




def sgn_single(x):
  return 1 if x > 0 else -1

def sgn(x):
  return np.where(x>0,1,-1)   


x1=np.array([0, 0, 1, 0, 1, 0, 0, 1])
x2=np.array([0, 0, 0, 0, 0, 1, 0, 0])
x3=np.array([0, 1, 1, 0, 0, 1, 0, 1])

x1 = sgn(x1)
x2 = sgn(x2)
x3 = sgn(x3)


dataInput = np.stack((x1,x2,x3))

nNodes = np.shape(dataInput)[1] # Gives us 8 neurons

# Set the coefficient matrix
weights = np.zeros((nNodes,nNodes)) # 8 X 8
nOfDataInputs = np.shape(dataInput)[0] # 3

for i in range(nNodes):
  for j in range(nNodes):
    #if i != j:
      for k in range(nOfDataInputs):
        weights[i,j] += dataInput[k,i]*dataInput[k,j]

print(weights)



def testPatterns(xVec, strVal):
  
  act = np.sum(weights*xVec,axis=1)
  xVec = sgn(act)
  return xVec


activation = np.zeros((nNodes,1))     
  

activation = dataInput[0,:]
a = testPatterns(activation, "x1")
print("x1")
print(np.array_equal(activation,a))

activation = dataInput[1,:]
b = testPatterns(activation, "x2")
print("x3")
print(np.array_equal(activation,b))

activation = dataInput[2,:]
c = testPatterns(activation, "x3")
print("x3")
print(np.array_equal(activation,c))

# Succeeds storing the patterns



[[ 3.  1. -1.  3.  1. -1.  3. -1.]
 [ 1.  3.  1.  1. -1.  1.  1.  1.]
 [-1.  1.  3. -1.  1. -1. -1.  3.]
 [ 3.  1. -1.  3.  1. -1.  3. -1.]
 [ 1. -1.  1.  1.  3. -3.  1.  1.]
 [-1.  1. -1. -1. -3.  3. -1. -1.]
 [ 3.  1. -1.  3.  1. -1.  3. -1.]
 [-1.  1.  3. -1.  1. -1. -1.  3.]]
x1
True
x3
True
x3
True


In [10]:
# New patterns
from copy import deepcopy

x1d=np.array([1, 0, 1, 0, 1, 0, 0, 1])
x2d=np.array([1, 1, 0, 0, 0, 1, 0, 0])
x3d=np.array([1, 1, 1, 0, 1, 1, 0, 1])
x4d=np.array([1, 0, 0, 1, 1, 0, 1, 0])

#x3=np.array([0, 1, 1, 0, 0, 1, 0, 1])


x1d = sgn(x1d)
x2d = sgn(x2d)
x3d = sgn(x3d)
x4d = sgn(x4d)
maxit = 50

def vis2(x):
  print(np.where(x>0,1,-0)   )

if(True):

  # Test convergance
  wrongData = np.stack((x1d, x2d, x3d, x4d))
  
  for i in range (np.shape(wrongData)[0]):
    toTest = wrongData[i,:]
    nOfTries = 0
    testStr = "x"+str(i+1)+"d"
    print("Starting "+str(i))
    
    activation = toTest
    toMatch = np.zeros((1,nNodes))
    
    print("starting")
    print(activation)
    print("match")
    print(toMatch)
    
    while(np.array_equal(activation, toMatch) == False and nOfTries < maxit):
      nOfTries +=1
      toMatch = deepcopy(activation)
      
      activation = testPatterns(toMatch, testStr)
      #print("OUTCOME OF " +str(i) + " tries " + str(nOfTries))
      #vis2(activation)
      #vis2(toMatch)
      
      
    if(nOfTries < 50):
      print(testStr + " converged at round " + str(nOfTries))
      vis2(activation)
      vis2(toMatch)
    else:
      print(testStr + " Did not converge after " + str(nOfTries)+" rounds.")
    

  #activation = x3d
  #x3d1 = testPatterns(activation, "x3d")
  #x3d2 = testPatterns(x3d1, "x3d")
  #x3d3 = testPatterns(x3d2, "x3d")
  
#Apply the update rule repeatedly until you reach a stable fixpoint. Did all the patterns converge towards stored patterns?
 # No, only managed to do it for point 1 ?
  
#How many attractors are there in this network? Hint: automate the searching.
  # 2 right?

#What happens when you make the starting pattern even more dissimilar to the stored ones (e.g. more than half is wrong)?  
  # Haven't tested, not sure why this is not working
  
  

Starting 0
starting
[ 1 -1  1 -1  1 -1 -1  1]
match
[[0. 0. 0. 0. 0. 0. 0. 0.]]
x1d converged at round 2
[0 0 1 0 1 0 0 1]
[0 0 1 0 1 0 0 1]
Starting 1
starting
[ 1  1 -1 -1 -1  1 -1 -1]
match
[[0. 0. 0. 0. 0. 0. 0. 0.]]
x2d converged at round 3
[0 0 0 0 0 1 0 0]
[0 0 0 0 0 1 0 0]
Starting 2
starting
[ 1  1  1 -1  1  1 -1  1]
match
[[0. 0. 0. 0. 0. 0. 0. 0.]]
x3d converged at round 3
[0 1 1 0 0 1 0 1]
[0 1 1 0 0 1 0 1]
Starting 3
starting
[ 1 -1 -1  1  1 -1  1 -1]
match
[[0. 0. 0. 0. 0. 0. 0. 0.]]
x4d converged at round 1
[1 0 0 1 1 0 1 0]
[1 0 0 1 1 0 1 0]


In [11]:
import itertools #import combinations

#a = itertools.permutations([0,1,0,1,0,1,0,1])
a = itertools.product([0, 1], repeat=8)
#print(list(a))
#finalArr = np.array([256,1])
count = 0


final = np.array([])
#print(type(np.asarray(list(a)[0])))

for x in list(a):
  
  activation = np.asarray(x)
  activation = sgn(activation)
  
  b = testPatterns(activation, "x2")
  if(np.array_equal(activation,b)):
      count = count + 1 
      print(np.asarray(x))
      
    
    
print("There are " + str(count)+ " attractors.")  

[0 0 0 0 0 1 0 0]
[0 0 0 0 1 0 0 0]
[0 0 1 0 0 0 0 1]
[0 0 1 0 0 1 0 1]
[0 0 1 0 1 0 0 1]
[0 1 1 0 0 1 0 1]
[1 0 0 1 0 1 1 0]
[1 0 0 1 1 0 1 0]
[1 0 1 1 1 0 1 1]
[1 1 0 1 0 0 1 0]
[1 1 0 1 0 1 1 0]
[1 1 0 1 1 0 1 0]
[1 1 1 1 0 1 1 1]
[1 1 1 1 1 0 1 1]
There are 14 attractors.


In [1]:
allArr = np.array(list(a))

for x in a:
  savedarr = x
  print(savedarr)
  #print(np.shape(savedarr))

NameError: ignored

In [0]:
a = np.array([1,2,3,3])

if 7 in a:
  print("yay")

In [196]:
lst = list(itertools.product([0, 1], repeat=8))
print(list(lst))

[(0, 0, 0, 0, 0, 0, 0, 0), (0, 0, 0, 0, 0, 0, 0, 1), (0, 0, 0, 0, 0, 0, 1, 0), (0, 0, 0, 0, 0, 0, 1, 1), (0, 0, 0, 0, 0, 1, 0, 0), (0, 0, 0, 0, 0, 1, 0, 1), (0, 0, 0, 0, 0, 1, 1, 0), (0, 0, 0, 0, 0, 1, 1, 1), (0, 0, 0, 0, 1, 0, 0, 0), (0, 0, 0, 0, 1, 0, 0, 1), (0, 0, 0, 0, 1, 0, 1, 0), (0, 0, 0, 0, 1, 0, 1, 1), (0, 0, 0, 0, 1, 1, 0, 0), (0, 0, 0, 0, 1, 1, 0, 1), (0, 0, 0, 0, 1, 1, 1, 0), (0, 0, 0, 0, 1, 1, 1, 1), (0, 0, 0, 1, 0, 0, 0, 0), (0, 0, 0, 1, 0, 0, 0, 1), (0, 0, 0, 1, 0, 0, 1, 0), (0, 0, 0, 1, 0, 0, 1, 1), (0, 0, 0, 1, 0, 1, 0, 0), (0, 0, 0, 1, 0, 1, 0, 1), (0, 0, 0, 1, 0, 1, 1, 0), (0, 0, 0, 1, 0, 1, 1, 1), (0, 0, 0, 1, 1, 0, 0, 0), (0, 0, 0, 1, 1, 0, 0, 1), (0, 0, 0, 1, 1, 0, 1, 0), (0, 0, 0, 1, 1, 0, 1, 1), (0, 0, 0, 1, 1, 1, 0, 0), (0, 0, 0, 1, 1, 1, 0, 1), (0, 0, 0, 1, 1, 1, 1, 0), (0, 0, 0, 1, 1, 1, 1, 1), (0, 0, 1, 0, 0, 0, 0, 0), (0, 0, 1, 0, 0, 0, 0, 1), (0, 0, 1, 0, 0, 0, 1, 0), (0, 0, 1, 0, 0, 0, 1, 1), (0, 0, 1, 0, 0, 1, 0, 0), (0, 0, 1, 0, 0, 1, 0, 1), (0, 0, 1, 0